kind: pipeline
name: default

image_pull_secrets:
  - image-registry-secret

platform:
  os: linux
  arch: amd64


steps:
  - name: build
    image: golang:1.17-buster
    environment:
      SSH_KEY:
        from_secret: ssh_key_github
    commands:
      - apt update
      - apt install -y git openssh-client build-essential
      - mkdir /root/.ssh
      - echo -n "$SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -H github.com >> /root/.ssh/known_hosts 2> /dev/null
#      - git clone git@github.com:everFinance/dapp-tools.git
#      - go env -w GOPRIVATE=github.com/everFinance/dapp-tools
      - go env -w CGO_ENABLED=0
      - go mod tidy
      - cd cmd/pay-server
      - go build
      - cd ../../cmd/watchmen
      - go build
      - cd ../../cmd/snapshot
      - go build
      - cd ../../cmd/execHub
      - go build
      - cd ../../cmd/explorer
      - go build
      - cd ../../cmd/mintbot
      - go build
    depends_on:
      - clone
  - name: publish-dev-pay
    image: plugins/docker
    daemon_off: true
    privileged: true
    settings:
      username:
        from_secret: docker_dev_username
      password:
        from_secret: docker_dev_password
      registry:
        from_secret: docker_dev_registry
      repo:
        from_secret: docker_dev_repo
      build_args:
        - MILLET_BUILD_ARG=dev
      tags:
        - ${DRONE_COMMIT_SHA}
        - ${DRONE_COMMIT_BRANCH/\//-}
        - dev
    depends_on:
      - build
    when:
      branch: [ feature/*,fix/* ]

  - name: publish-dev-watchmen
    image: plugins/docker
    daemon_off: true
    privileged: true
    settings:
      username:
        from_secret: docker_dev_username
      password:
        from_secret: docker_dev_password
      registry:
        from_secret: docker_dev_registry
      repo:
        from_secret: docker_dev_repo_watchmen
      build_args:
        - MILLET_BUILD_ARG=dev
      tags:
        - ${DRONE_COMMIT_SHA}
        - ${DRONE_COMMIT_BRANCH/\//-}
        - dev
      dockerfile: Dockerfile.watchmen
    depends_on:
      - build
      - publish-dev-pay
    when:
      branch: [ feature/*,fix/* ]

  - name: publish-dev-snap
    image: plugins/docker
    daemon_off: true
    privileged: true
    settings:
      username:
        from_secret: docker_dev_username
      password:
        from_secret: docker_dev_password
      registry:
        from_secret: docker_dev_registry
      repo:
        from_secret: docker_dev_repo_snap
      build_args:
        - MILLET_BUILD_ARG=dev
      tags:
        - ${DRONE_COMMIT_SHA}
        - ${DRONE_COMMIT_BRANCH/\//-}
        - dev
      dockerfile: Dockerfile.snap
    depends_on:
      - build
      - publish-dev-watchmen
    when:
      branch: [ feature/*,fix/* ]

  - name: publish-dev-exechub
    image: plugins/docker
    daemon_off: true
    privileged: true
    settings:
      username:
        from_secret: docker_dev_username
      password:
        from_secret: docker_dev_password
      registry:
        from_secret: docker_dev_registry
      repo:
        from_secret: docker_dev_repo_exechub
      build_args:
        - MILLET_BUILD_ARG=dev
      tags:
        - ${DRONE_COMMIT_SHA}
        - ${DRONE_COMMIT_BRANCH/\//-}
        - dev
      dockerfile: Dockerfile.execHub
    depends_on:
      - build
      - publish-dev-snap
    when:
      branch: [ feature/*,fix/* ]

  - name: publish-dev-explorer
    image: plugins/docker
    daemon_off: true
    privileged: true
    settings:
      username:
        from_secret: docker_dev_username
      password:
        from_secret: docker_dev_password
      registry:
        from_secret: docker_dev_registry
      repo:
        from_secret: docker_dev_repo_explorer
      build_args:
        - MILLET_BUILD_ARG=dev
      tags:
        - ${DRONE_COMMIT_SHA}
        - ${DRONE_COMMIT_BRANCH/\//-}
        - dev
      dockerfile: Dockerfile.explorer
    depends_on:
      - build
      - publish-dev-exechub
    when:
      branch: [ feature/*,fix/* ]

  - name: publish-dev-mintbot
    image: plugins/docker
    daemon_off: true
    privileged: true
    settings:
      username:
        from_secret: docker_dev_username
      password:
        from_secret: docker_dev_password
      registry:
        from_secret: docker_dev_registry
      repo:
        from_secret: docker_dev_repo_mintbot
      build_args:
        - MILLET_BUILD_ARG=dev
      tags:
        - ${DRONE_COMMIT_SHA}
        - ${DRONE_COMMIT_BRANCH/\//-}
        - dev
      dockerfile: Dockerfile.mintbot
    depends_on:
      - build
      - publish-dev-explorer
    when:
      branch: [ feature/*,fix/* ]

  - name: deploy-dev-pay
    image: quay.io/honestbee/drone-kubernetes
    daemon_off: true
    privileged: true
    settings:
      kubernetes_server:
        from_secret: kube_dev_api
      kubernetes_token:
        from_secret: kube_dev_token
      kubernetes_cert:
        from_secret: kube_dev_cert
      repo:
        from_secret: docker_dev_repo
      namespace: biz
      deployment: everpay-dev
      container: server
      tag: ${DRONE_COMMIT_SHA}
    depends_on:
      - publish-dev-pay
    when:
      branch: [ feature/*,fix/* ]

  - name: deploy-dev-watchmen
    image: quay.io/honestbee/drone-kubernetes
    daemon_off: true
    privileged: true
    settings:
      kubernetes_server:
        from_secret: kube_dev_api
      kubernetes_token:
        from_secret: kube_dev_token
      kubernetes_cert:
        from_secret: kube_dev_cert
      repo:
        from_secret: docker_dev_repo_watchmen
      namespace: biz
      deployment: [everpay-watchmen-01-dev,everpay-watchmen-02-dev,everpay-watchmen-03-dev]
      container: watchmen
      tag: ${DRONE_COMMIT_SHA}
    depends_on:
      - publish-dev-watchmen
    when:
      branch: [ feature/*,fix/* ]

  - name: deploy-dev-snap
    image: quay.io/honestbee/drone-kubernetes
    daemon_off: true
    privileged: true
    settings:
      kubernetes_server:
        from_secret: kube_dev_api
      kubernetes_token:
        from_secret: kube_dev_token
      kubernetes_cert:
        from_secret: kube_dev_cert
      repo:
        from_secret: docker_dev_repo_snap
      namespace: biz
      deployment: everpay-snap-dev
      container: snap
      tag: ${DRONE_COMMIT_SHA}
    depends_on:
      - publish-dev-snap
    when:
      branch: [ feature/*,fix/* ]

  - name: deploy-dev-exechub
    image: quay.io/honestbee/drone-kubernetes
    daemon_off: true
    privileged: true
    settings:
      kubernetes_server:
        from_secret: kube_dev_api
      kubernetes_token:
        from_secret: kube_dev_token
      kubernetes_cert:
        from_secret: kube_dev_cert
      repo:
        from_secret: docker_dev_repo_exechub
      namespace: biz
      deployment: everpay-exechub-dev
      container: exechub
      tag: ${DRONE_COMMIT_SHA}
    depends_on:
      - publish-dev-exechub
    when:
      branch: [ feature/*,fix/* ]

  - name: deploy-dev-explorer
    image: quay.io/honestbee/drone-kubernetes
    daemon_off: true
    privileged: true
    settings:
      kubernetes_server:
        from_secret: kube_dev_api
      kubernetes_token:
        from_secret: kube_dev_token
      kubernetes_cert:
        from_secret: kube_dev_cert
      repo:
        from_secret: docker_dev_repo_explorer
      namespace: biz
      deployment: everpay-explorer-dev
      container: explorer
      tag: ${DRONE_COMMIT_SHA}
    depends_on:
      - publish-dev-explorer
    when:
      branch: [ feature/*,fix/* ]

  - name: deploy-dev-mintbot
    image: quay.io/honestbee/drone-kubernetes
    daemon_off: true
    privileged: true
    settings:
      kubernetes_server:
        from_secret: kube_dev_api
      kubernetes_token:
        from_secret: kube_dev_token
      kubernetes_cert:
        from_secret: kube_dev_cert
      repo:
        from_secret: docker_dev_repo_mintbot
      namespace: biz
      deployment: everpay-mintbot-dev
      container: mintbot
      tag: ${DRONE_COMMIT_SHA}
    depends_on:
      - publish-dev-mintbot
    when:
      branch: [ feature/*,fix/* ]

  - name: publish-prod-pay
    image: plugins/docker
    daemon_off: true
    privileged: true
    environment:
      SSH_KEY:
        from_secret: ssh_key_github
    settings:
      username:
        from_secret: docker_production_username
      password:
        from_secret: docker_production_password
      registry:
        from_secret: docker_production_registry
      repo:
        from_secret: docker_production_repo
      build_args:
        - MILLET_BUILD_ARG=prod
      tags:
        - main
        - ${DRONE_TAG=latest}
        - ${DRONE_COMMIT_SHA}
    depends_on:
      - build
    when:
      event:
        - tag

  - name: publish-prod-watchmen
    image: plugins/docker
    daemon_off: true
    privileged: true
    settings:
      username:
        from_secret: docker_production_username
      password:
        from_secret: docker_production_password
      registry:
        from_secret: docker_production_registry
      repo:
        from_secret: docker_production_repo_watchmen
      build_args:
        - MILLET_BUILD_ARG=prod
      tags:
        - main
        - ${DRONE_TAG=latest}
        - ${DRONE_COMMIT_SHA}
      dockerfile: Dockerfile.watchmen
    depends_on:
      - build
      - publish-prod-pay
    when:
      event:
        - tag

  - name: publish-prod-snap
    image: plugins/docker
    daemon_off: true
    privileged: true
    settings:
      username:
        from_secret: docker_production_username
      password:
        from_secret: docker_production_password
      registry:
        from_secret: docker_production_registry
      repo:
        from_secret: docker_production_repo_snap
      build_args:
        - MILLET_BUILD_ARG=prod
      tags:
        - main
        - ${DRONE_TAG=latest}
        - ${DRONE_COMMIT_SHA}
      dockerfile: Dockerfile.snap
    depends_on:
      - build
      - publish-prod-watchmen
    when:
      event:
        - tag

  - name: publish-prod-exechub
    image: plugins/docker
    daemon_off: true
    privileged: true
    settings:
      username:
        from_secret: docker_production_username
      password:
        from_secret: docker_production_password
      registry:
        from_secret: docker_production_registry
      repo:
        from_secret: docker_production_repo_exechub
      build_args:
        - MILLET_BUILD_ARG=prod
      tags:
        - main
        - ${DRONE_TAG=latest}
        - ${DRONE_COMMIT_SHA}
      dockerfile: Dockerfile.execHub
    depends_on:
      - build
      - publish-prod-snap
    when:
      event:
        - tag

  - name: publish-prod-explorer
    image: plugins/docker
    daemon_off: true
    privileged: true
    settings:
      username:
        from_secret: docker_production_username
      password:
        from_secret: docker_production_password
      registry:
        from_secret: docker_production_registry
      repo:
        from_secret: docker_production_repo_explorer
      build_args:
        - MILLET_BUILD_ARG=prod
      tags:
        - main
        - ${DRONE_TAG=latest}
        - ${DRONE_COMMIT_SHA}
      dockerfile: Dockerfile.explorer
    depends_on:
      - build
      - publish-prod-exechub
    when:
      event:
        - tag

  - name: publish-prod-mintbot
    image: plugins/docker
    daemon_off: true
    privileged: true
    settings:
      username:
        from_secret: docker_production_username
      password:
        from_secret: docker_production_password
      registry:
        from_secret: docker_production_registry
      repo:
        from_secret: docker_production_repo_mintbot
      build_args:
        - MILLET_BUILD_ARG=prod
      tags:
        - main
        - ${DRONE_TAG=latest}
        - ${DRONE_COMMIT_SHA}
      dockerfile: Dockerfile.mintbot
    depends_on:
      - build
      - publish-prod-explorer
    when:
      event:
        - tag